### PR TITLE
db schema for B+ changed so pinID is true board pin# 

### PR DESCRIPTION
**Pull request by Paku-**
This is just and idea how the board table should looks like.

Pls do not merge it it's just for your review.

Have no idea if the service script will work on it or no, pls look closer if we can use it.
(you can grab branch from my repo)

In simple words the db should correspond to the true board logic ..

Other thing is that boards are compatible on the pin level so v1 up to v3 should work on the same table but using limited rows access.

### CODE REVIEW

**Comment by Paku-** [comment]
demo script changed added in 4d3cb06

**Comment by Paku-** [comment]
I'm working on db and script hope you are not doing the same ...

**Comment by Paku-** [comment]
Does the script only sets pins in OUT mode if enabled ???

**Comment by linwiz** [comment]
yes

**Comment by Paku-** [comment]
So we have to cover the IN pins as well ...

**Comment by linwiz** [comment]
Eventually, yes but I am trying to take this one step at a time

**Comment by Paku-** [comment]
sure ...

**Comment by linwiz** [comment]
Was there a reason you chose `WHERE concat('',pinNumberBCM * 1) = pinNumberBCM` and not `WHERE pinNumberBCM REGEXP '[0-9]+';`?

**Comment by Paku-** [comment]
isn't it the same ??, just found somewhere it's faster .. and I hate regexpr as the bash as well (nor I'm good in it)....
BTW it took me 1h to find how to put line elements into the array ... >>> arr=($this_pin) 
.. hate scripts ...

**Comment by linwiz** [comment]
The end result is the same, I didn't know concat was faster. I suck at regex as well but sometimes regex is the way to go.

**Comment by Paku-** [comment]
Have the idea how to make script faster but I am to short on bash knowlage will push my work here. Look at it you will finish it much faster ... The main idea is to limit mySQL CLI calls to just one inside the loop.

**Comment by Paku-** [comment]
Create new branch and merge it into it. Then after edit you can merge into ajax.

**Comment by Paku-** [comment]
I am here so can help on git.

**Comment by Paku-** [comment]
or just checkout the db_update branch from my repo then pull the request. I will then sent it to ajax ...

**Comment by Paku-** [comment]
@linwiz OK ??

**Comment by linwiz** [comment]
You're definitely helping. I like the work you are doing, and good catch on the speed update, maybe the other mysql calls can be done away with also.

**Comment by Paku-** [comment]
thanks .. can you finish it ??

**Comment by linwiz** [comment]
I think so lol

**Comment by Paku-** [comment]
but you have merge into ajax ... is there any option to merge into NEW branch (on github) ?? If no it's ok, but now ajax head is filled with broken code /not runnig/ so if any other dev would like to help, he will get not running code what's bad for master like branch ... good there are only two of us here :)

**Comment by Paku-** [comment]
Check out the details, so B and B+ (v2 and v3) boards are pinout compatible. It means we do not need separate tables for them we just have to limit the first select in the service so for v2 we only see pins 1-26 while for v3 1-40.

**Comment by linwiz** [comment]
In that case, the RPi Compute module with like 60 gpios can use the v2 table as well.

**Pull request merged**
