### PR TITLE
Log Paging

### PR DESCRIPTION
**Pull request by Paku-**
This is first step of the Log Paging functionality.
I'm creating this pull request as it seems to me you are going to move ajax folder, I expect some merge problems (hope there will be no problems ...)
If you can pls merge this before merging your Ajax branch (so moving folders).

If you can't just reject this pull.

Changes:
- two config directives added:

    //UI configuration
    $logPaging=10; //lines per screen
    $debugMode=1; //enable UI debug output

- little code moving and cleaning.

### CODE REVIEW

**Comment by Paku-** [comment]
I can see you added most of changes and assume Ajax branch is the one I should work on now ???

**Comment by linwiz** [comment]
That is correct.

**Comment by Paku-** [comment]
The problem started here, it should be merged into new ajax branch. Could be it was my fault as I should choose other branch as destination. Anyway for now our temp master is ajax but both of us should use other branches for work any just merge when some part is done. You may create the new "login" branch so at any time both of us will be able to merge something new to ajax.There is alway kind of master you start from and merge the work results back.

**Comment by linwiz** [comment]
So is it safe to merge my login branch into the ajax branch?

**Pull request closed without merging**
