### PR TITLE
Log paging

### PR DESCRIPTION
**Pull request by Paku-**
Hi,
I rebased my log_paging branch over yours new ajax (had to cut it off the main master on put over the new ajax one). 
Now new ajax is our temporal "master" for work.

All this commits just clear stuff.
There are little code changes, described below.

This one is important: 
"- added second index_paku.php entry point so I can get in while you work on login.php" 

Have in mind to merge this one only into AJAX !!!
(not master)

### CODE REVIEW

**Comment by Paku-** [comment]
github
That's how it looks from my point of view.
It seems you could lost history for one of the branches ... one in left lower corner.

-upstream/* your repo on github
- origin/* my repo on github
rest are my local copies

**Comment by linwiz** [comment]
These commits are redoing work that has already been included, and they are recreating the files in the ajax folder which no longer exists. I don't understand whats going on with the gh-pages, I see a full history in https://github.com/linwiz/Raspberry-Pi-Web-GPIO/commits/gh-pages

I seem to be making a mess of everything, I am not used to someone trying to work on the same code that I am trying to work on. Maybe I will get this figured out

**Comment by Paku-** [comment]
It may looks like that but just click to merge it. Yes after the mess there were 2 file in ajax folder I then deleted them no it's clear. You my checkout my log_paging branch and check it out :)

**Comment by Paku-** [comment]
You will - just take care to protect master branch from unwanted merges (like last time).
Alway work on other branch never on master (have other branch to be the same what you ahve on disk /local copy/)

gh-pages seem ok, sorry, have a look at "graphs" then "network" on the left menu.

**Comment by Paku-** [comment]
Once you merged I always delete the merged branch. So next part of work starts from top of the tree (top of ajax here). That's always good idea for git to start new branch for new task, merge often and fast then delete (after task is complete) so it will no mess your point of view :)

**Pull request merged**
