### PR TITLE
Improved performance by reducing mysql querys

### PR DESCRIPTION
**Pull request by linwiz**

### CODE REVIEW

**Comment by Paku-** [comment]
Have you tested this ??
You may remove echos as well

**Comment by linwiz** [comment]
It is working for my rev2 Pi

**Comment by Paku-** [comment]
Importing docs/gpio.sql into database user@localhost/gpio
    ERROR 1062 (23000) at line 52: Duplicate entry '1' for key 'PRIMARY'

we lost my gpio.sql somewhere ...

**Comment by Paku-** [comment]
yes gpio.sql is not mine, 

there is no DROP commands., nor 
     KEY `pinNumber` (`pinNumberBCM`)

for rev3 tbl

**Comment by linwiz** [comment]
This was your [commit](https://github.com/Paku-/Raspberry-Pi-Web-GPIO/blob/5520a5753cbfcefea6114b886223c2ab25dac986/docs/gpio.sql)

Unfortunately as you can see [pinNumberBCM](https://github.com/Paku-/Raspberry-Pi-Web-GPIO/blob/5520a5753cbfcefea6114b886223c2ab25dac986/docs/gpio.sql#L135) cannot be unique because of the 'X' values that are assigned for non GPIO pins.

I removed the drop command because it will erase someones pin descriptions if they choose to customize them.

**Comment by Paku-** [comment]
So, as I remember I left the non uniq index there ...
On drop: so script is not able to update the the database ...
We need a solution for one press db update ...

**Comment by linwiz** [comment]
It is possible, the [drupal](http://drupal.org/) content management system allows for automatic database updates. I don't know the technical parts of how it works though.

**Comment by Paku-** [comment]
So maybe you can add a question if some one wants to update the base.

One more: we can remove sleep 0.2 now as there is only one select.

**Pull request merged**
